language: python
sudo: required
arch:
  - amd64
services:
- docker
env:
  matrix:
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.5.0 TAG=py2tf1.5
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.5.0 TAG=py3tf1.5
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.11.0 TAG=py2tf1.11
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.11.0 TAG=py3tf1.11
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.12.0 TAG=py2tf1.12
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.12.0 TAG=py3tf1.12
  global:
  - secure: XCR18PWpYyD0cQHlJpYy5/u6UWcRe11xcJCLtYoEX1kSwbmwSLmneduI12QaUErclsMaAc/Y6hBHMgMUVkyjWP0ES9A8EF/kW+kKFsaVf4EEo2qjWAj3Nn659NF8ymfAQyy7QOvx7UfQttsndM2qurMK0mFtGjkKpeQe9vY7hO9HppvSFMkgWDLJU8vrgTdQRSFkqbOlNl6Rsyl8ES+n7aNq5iVCyGrRXQrMssJXWDbERlm+mB8RBIuo0nMqG0pdf0+6nEg/5i16KLGVh7rdmgtoiY8TWMwcFkig6ZE5t7TRdjzmb8R2bD+G/W4Al/PEHobI+3+8n8kWvzEw1u7dkH3o3UQ5i/bhSTfDBDY7GGMK4KiAMg7fve8wBUh5Rh1mlTCYh36cAsPKQIGXQQ0GuFZR99R3wePjIgGSeScQeNtNf7vp3ly6Q7mngrwEiTqyH80kYu7gLxqU8hJRQ6fQN37OCUq/OxOMPYYW8QaldQZXkjLAFLdFfuvzs3znRcCQeXKf1JIdZe4AzBxEF/N6Hqh5mRPK1Zev90QQXaG6SeX/yN7IGzECz+kdJHvH7F1Mu0vhHRvd09Zsa+a59u43tdYSQo8nzhejtjmE5JpG1DoZwxx/WpSydfI7/ef96pnHtghh8nfPeCEIeo0MZhfneS+zhwB75PenUmkPzvUfKD8=
  - secure: PYGVGSBDJeL66a1Ua+AAM0CwhuT199fj58QAn/FWVYIO3vUgNvm3w8LZLfWkRWRGTwBmSNGZO+ysgvwIXboEW49LvgDKv30Pe9QqtxyomhqXmYo1L19Pm10FkfT1jp0/AHouySnPZSChyR/lYt2fysTmSR/2q+1aHzl9b42R3aqp0Wbks+RZkRss7tspnvwj1drKIHTWSAeBje7rPuEBhk4aluqbOaQ6k9HDs05iHJev8C7hkLELmMguXX/VMMG7047BErKrMn97Zg4Myx6Tu2cqkRpOrQ/jGY/0GWCcIFo0SbOJMfNi6mgDyFWNtPre8t2fIqonapnLZMlTuIXERMEyMYUo/8HV7VHTOARnz7XsRVvXuBSF1hR6lyLalv6iYjx+j1rKYr3PS8T/rirwOFADThl2yppZmjbgK3tfY6OyVUwBbWXw7W/MW5jVQzWx4M5Ft7Use6VZJQOB4xBB4s3Yie/d7Aua66/Jm6bpNh7hr+UssSrD+c2APfIcWPYdEoo/XuetGt9Tn4yqQTlNAAkkRkgpQK2aqbVOWrg1ZiD5WcrJvWC0Agvgy62WfF4HCayILiSuKkLa906PeC3JiS6Noa9eLOBCKOrjwUtn8he0VB1cZrek4vKb8GepWRHPttHrXj8Is/MxfD1OGCBghoZBcRvQTLHxhyca+4r7Uys=
install:
- export REPO="haowenxu/travis-tensorflow-docker"
- docker build -t "${REPO}:${TAG}" "${TAG}"
script:
- docker run -v "$(pwd)":"$(pwd)" -w "$(pwd)" -e PYTHON_VERSION="${PYTHON_VERSION}"
  -e TENSORFLOW_VERSION="${TENSORFLOW_VERSION}" "${REPO}:${TAG}" python tests.py
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
- docker push "${REPO}:${TAG}"
